### ISSUE TITLE
No such file or directory: 'sentiment.csv'

### ISSUE THREAD

**Issue by anfas313** [ayushoriginal/Sentiment-Analysis-Twitter#3]
Traceback (most recent call last):
  File "sentiment.py", line 457, in <module>
    main(sys.argv[1:])
  File "sentiment.py", line 426, in main
    tweets1 = sanderstwitter02.getTweetsRawData('sentiment.csv')
  File "/home//Desktop/Sentiment-Analysis-Twitter-master/Sentiment-Analysis-Twitter-master/sanderstwitter02/__init__.py", line 12, in getTweetsRawData
    fp = open( fileName, 'rb' )
IOError: [Errno 2] No such file or directory: 'sentiment.csv'

**Comment by rajitnair** [comment]
Dear,
       Did you get the solution

**Comment by deepdipu** [comment]
yaah same here it shows the error sentiment.csv file not found

**Comment by balajitk7** [comment]
please upload sentiment.csv file
